name: testing
run-name: ${{ github.actor }} is running the API testing suite
on:
  pull_request:
    branches:    
      - main
      - develop
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm install
      - run: npm run test
